### ISSUE TITLE
Build Faild On iOS

### ISSUE THREAD

**Issue by orangeagain** [guycalledfrank/xatlasLib#3]
My unity File Struct:
\Plugins\iOS\xatlas.cpp
\Plugins\iOS\xatlas.h
\Plugins\iOS\xatlas_c.h

edit xatlas.cs:
[DllImport ("xatlasLib", CallingConvention=CallingConvention.Cdecl)]
to
[DllImport ("__Internal", CallingConvention=CallingConvention.Cdecl)]

than compile unity project in xcode,print 12 errors blow:
`   + [arm64] Linking UnityFramework...
ld: warning: arm64 function not 4-byte aligned: _unwind_tester from Libraries\libiPhone-lib.a(unwind_test_arm64.o)
Undefined symbols for architecture arm64:
  "_xatlasCreateAtlas", referenced from:
      _xatlas_xatlasCreateAtlas_m9F6FC3423AC0B1507184F8C09C95F46FB4BBF88F in Assembly-CSharp-firstpass.cpp.obj
      _xatlas_Unwrap_m802775D37FBE07E5D156FF53BF6A3DD5D49085E7 in Assembly-CSharp-firstpass.cpp.obj
     (maybe you meant: _xatlas_xatlasCreateAtlas_m9F6FC3423AC0B1507184F8C09C95F46FB4BBF88F)
  "_xatlasGetAtlasIndex", referenced from:
      _xatlas_xatlasGetAtlasIndex_m0CCAE558A035BA6441F9D7D2ED707375A098FAFF in Assembly-CSharp-firstpass.cpp.obj
     (maybe you meant: _xatlas_xatlasGetAtlasIndex_m0CCAE558A035BA6441F9D7D2ED707375A098FAFF)
  "_xatlasAddUVMesh", referenced from:
      _xatlas_xatlasAddUVMesh_m1F7FCBBD0147EF2F1DF7DAE8DBE5B5EFA9DF40BD in Assembly-CSharp-firstpass.cpp.obj
     (maybe you meant: _xatlas_xatlasAddUVMesh_m1F7FCBBD0147EF2F1DF7DAE8DBE5B5EFA9DF40BD)
  "_xatlasGetAtlasCount", referenced from:
      _xatlas_xatlasGetAtlasCount_m9A86D46FED32309AAADA55661D46680EA25960A3 in Assembly-CSharp-firstpass.cpp.obj
     (maybe you meant: _xatlas_xatlasGetAtlasCount_m9A86D46FED32309AAADA55661D46680EA25960A3)
  "_xatlasAddMesh", referenced from:
      _xatlas_xatlasAddMesh_mF5F0320F2B1860E6C215CDBFE6A2CE115FBE3B3E in Assembly-CSharp-firstpass.cpp.obj
      _xatlas_Unwrap_m802775D37FBE07E5D156FF53BF6A3DD5D49085E7 in Assembly-CSharp-firstpass.cpp.obj
     (maybe you meant: _xatlas_xatlasAddMesh_mF5F0320F2B1860E6C215CDBFE6A2CE115FBE3B3E)
  "_xatlasParametrize", referenced from:
      _xatlas_xatlasParametrize_m20F95ED4808596651DE0B1F0BF2A8FD83F51ADA7 in Assembly-CSharp-firstpass.cpp.obj
      _xatlas_Unwrap_m802775D37FBE07E5D156FF53BF6A3DD5D49085E7 in Assembly-CSharp-firstpass.cpp.obj
     (maybe you meant: _xatlas_xatlasParametrize_m20F95ED4808596651DE0B1F0BF2A8FD83F51ADA7)
  "_xatlasGetVertexCount", referenced from:
      _xatlas_xatlasGetVertexCount_m7DFA5121E9DD4387EDCAF2B7E220E2087AFB00D7 in Assembly-CSharp-firstpass.cpp.obj
      _xatlas_Unwrap_m802775D37FBE07E5D156FF53BF6A3DD5D49085E7 in Assembly-CSharp-firstpass.cpp.obj
     (maybe you meant: _xatlas_xatlasGetVertexCount_m7DFA5121E9DD4387EDCAF2B7E220E2087AFB00D7)
  "_xatlasClear", referenced from:
      _xatlas_xatlasClear_m8290FB30AD17F5CE7D5A78FA5421835177887D32 in Assembly-CSharp-firstpass.cpp.obj
      _xatlas_Unwrap_m802775D37FBE07E5D156FF53BF6A3DD5D49085E7 in Assembly-CSharp-firstpass.cpp.obj
     (maybe you meant: _xatlas_xatlasClear_m8290FB30AD17F5CE7D5A78FA5421835177887D32)
  "_xatlasPack", referenced from:
      _xatlas_xatlasPack_m05EFE7D4FC4FDFF567FF6A5699FF03915AD080C5 in Assembly-CSharp-firstpass.cpp.obj
      _xatlas_Unwrap_m802775D37FBE07E5D156FF53BF6A3DD5D49085E7 in Assembly-CSharp-firstpass.cpp.obj
     (maybe you meant: _xatlas_xatlasPack_m05EFE7D4FC4FDFF567FF6A5699FF03915AD080C5)
  "_xatlasNormalize", referenced from:
      _xatlas_xatlasNormalize_mB03652469DB319858DED018EAD3B1A0D0E8FD947 in Assembly-CSharp-firstpass.cpp.obj
      _xatlas_Unwrap_m802775D37FBE07E5D156FF53BF6A3DD5D49085E7 in Assembly-CSharp-firstpass.cpp.obj
     (maybe you meant: _xatlas_xatlasNormalize_mB03652469DB319858DED018EAD3B1A0D0E8FD947)
  "_xatlasGetIndexCount", referenced from:
      _xatlas_xatlasGetIndexCount_m4D35E2A4BCEB2CC07F6055B21F9006AA9662E833 in Assembly-CSharp-firstpass.cpp.obj
      _xatlas_Unwrap_m802775D37FBE07E5D156FF53BF6A3DD5D49085E7 in Assembly-CSharp-firstpass.cpp.obj
     (maybe you meant: _xatlas_xatlasGetIndexCount_m4D35E2A4BCEB2CC07F6055B21F9006AA9662E833)
  "_xatlasGetData", referenced from:
      _xatlas_xatlasGetData_m13F5E6596D6D1A4D7774A384FFF435C0D4F6518E in Assembly-CSharp-firstpass.cpp.obj
      _xatlas_Unwrap_m802775D37FBE07E5D156FF53BF6A3DD5D49085E7 in Assembly-CSharp-firstpass.cpp.obj
     (maybe you meant: _xatlas_xatlasGetData_m13F5E6596D6D1A4D7774A384FFF435C0D4F6518E)
ld: 12 symbol(s) not found for architecture arm64`

try compile xatlas.cpp with two .h files to ios static library xatlasLib.a ,and unity call .a file.compile unity project show same 12 errors too.

can you help me slove this problem? thanks very much.

**Comment by guycalledfrank** [comment]
Sorry, no idea, never compiled anything for iOS. I guess the way library functions are declared (_declspec(dllexport) _cdecl) is not the one apple interfaces expect. dllexport is windows-specific AFAIK.

**Comment by orangeagain** [comment]
I solve this ploblem.
the way is enable embed opeion.

**Comment by alfiolocastro** [comment]
> I solve this ploblem. the way is enable embed opeion.

Can you please be more specific? How did you managed to solve the issue?

**Comment by orangeagain** [comment]
> > I solve this ploblem. the way is enable embed opeion.
> 
> Can you please be more specific? How did you managed to solve the issue?

here is my build for apple platform
[https://github.com/orangeagain/UVAtlas-For-unity](https://github.com/orangeagain/UVAtlas-For-unity)

**Comment by guycalledfrank** [comment]
UVAtlas is not xatlas though...

**Comment by alfiolocastro** [comment]
> > > I solve this ploblem. the way is enable embed opeion.
> > 
> > 
> > Can you please be more specific? How did you managed to solve the issue?
> 
> here is my build for apple platform https://github.com/orangeagain/UVAtlas-For-unity

Thanks for the fast reply. Tried this yesterday. It works but it's much slower than the xatlas version. A mesh with 50k+ vertices took me several minutes instead of 2 seconds. Looks like it's a different source? (uvatlas instead of xatls)

**Comment by orangeagain** [comment]
> > > > I solve this ploblem. the way is enable embed opeion.
> > > 
> > > 
> > > Can you please be more specific? How did you managed to solve the issue?
> > 
> > 
> > here is my build for apple platform https://github.com/orangeagain/UVAtlas-For-unity
> 
> Thanks for the fast reply. Tried this yesterday. It works but it's much slower than the xatlas version. A mesh with 50k+ vertices took me several minutes instead of 2 seconds. Looks like it's a different source? (uvatlas instead of xatls)

Sorry, I mixed up these two libraries. I've also forgotten how to fix the error due to the long time that has passed.
